name: Check Sync with Main

on:
  pull_request:
    types: [synchronize, opened, reopened]
  push:
    branches:
      - main

jobs:
  check-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Fetch main branch
      run: |
        git fetch origin main

    - name: Check if branch is up-to-date with main
      run: |
        git merge-base --is-ancestor origin/main HEAD
    - name: Fail if not up-to-date
      if: failure()
      run: |
        echo "The branch is not up-to-date with main. Please rebase or merge main into your branch."
        exit 1
